---
name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash  # Set bash as the default shell for all run commands

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
            ${{ runner.os }}-poetry-
          path: |
            ~/.cache/pypoetry

      - name: Install Python dependencies
        run: poetry install --all-extras

      - name: Lint
        run: poetry run isort --check . && poetry run black --check . && poetry run flake8 --config setup.cfg . && poetry run mypy --config-file pyproject.toml .

      - name: Test
        run: source test.env && poetry run pytest -vv tests -p no:warnings
        env:
          CI: true
